const weaponMerchant = [
    {
        id: 'weaponMerchant',
        title: 'Weapons Merchant',
        items: [
            {
                id: 101,
                type: SHIP_ONLY,
                price: 225,
                finally: false,
                name: 'Rocket Cannon',
                img: 'HumanArtilleryUpOne',
                reforgedImg: 'RHumanArtilleryUpOne',
                doubledName: 'Double Rocket Cannon',
                doubledImg: 'DoubleRocketCannon',
                doubledReforgedImg: '',
                damage: 3,
                range: 1500,
                cooldown: 0.5,
                dps: 6
            },{
                id: 102,
                type: SHIP_STRUCTURES,
                price: 600,
                finally: false,
                name: 'Arrow Cannon',
                img: 'SteelRanged',
                reforgedImg: '',
                doubledName: 'Double Arrow Cannon',
                doubledImg: 'DoubleArrowCannon',
                doubledReforgedImg: '',
                damage: 10,
                range: 850,
                cooldown: 0.5,
                dps: 20
            },{
                id: 103,
                type: SHIP_STRUCTURES,
                price: 320,
                finally: false,
                name: 'Basic Cannon',
                img: 'DwarvenLongRifle',
                reforgedImg: '',
                doubledName: 'Double Basic Cannon',
                doubledImg: 'DoubleBasicCannon',
                doubledReforgedImg: '',
                damage: 20,
                range: 700,
                cooldown: 1.5,
                dps: 13
            },{
                id: 104,
                type: SHIP_ONLY,
                price: 450,
                finally: false,
                name: 'Flame Cannon',
                img: 'FireForTheCannon',
                reforgedImg: '',
                doubledName: 'Double Flame Cannon',
                doubledImg: 'DoubleFlameCannon',
                doubledReforgedImg: '',
                damage: 50,
                range: 800,
                cooldown: 3,
                dps: 16.6
            },{
                id: 105,
                type: SHIP_STRUCTURES,
                price: 600,
                finally: false,
                name: 'Cruiser Cannon',
                img: 'GoblinBlaster',
                reforgedImg: '',
                doubledName: 'Double Cruiser Cannon',
                doubledImg: 'DoubleCruiserCannon',
                doubledReforgedImg: '',
                damage: 30,
                range: 900,
                cooldown: 1.5,
                dps: 20
            },{
                id: 106,
                type: SHIP_ONLY,
                price: 700,
                finally: false,
                name: 'Multi-Rocket Cannon',
                img: 'ClusterRockets',
                reforgedImg: '',
                doubledName: 'Multi-Multi-Rocket Cannon',
                doubledImg: 'MultiMultiRocketCannon',
                doubledReforgedImg: '',
                damage: 15,
                range: 500,
                cooldown: 0.5,
                dps: 30
            },{
                id: 107,
                type: SHIP_STRUCTURES,
                price: 1750,
                finally: false,
                name: 'Bowmen Crew',
                img: 'ImprovedBows',
                reforgedImg: '',
                doubledName: 'Two Bowmen Crews',
                doubledImg: 'TwoBowmenCrews',
                doubledReforgedImg: '',
                damage: 10,
                range: 950,
                cooldown: 0.2,
                dps: 50
            },{
                id: 108,
                type: SHIP_STRUCTURES,
                price: 1220,
                finally: false,
                name: 'Cold-Arrows Cannon',
                img: 'ColdArrows',
                reforgedImg: '',
                doubledName: 'Double Cold-Arrows Cannon',
                doubledImg: 'DoubleColdArrowsCannon',
                doubledReforgedImg: '',
                damage: 40,
                range: 700,
                cooldown: 1,
                dps: 40
            },{
                id: 109,
                type: SHIP_STRUCTURES,
                price: 2050,
                finally: false,
                name: 'Machinegun Cannon',
                img: 'FlakCannons',
                reforgedImg: '',
                doubledName: 'Submachinegun',
                doubledImg: 'DoubleMachinegunCannon',
                doubledReforgedImg: '',
                damage: 10,
                range: 500,
                cooldown: 0.15,
                dps: 66.6
            },{
                id: 110,
                type: SHIP_ONLY,
                price: 1500,
                finally: false,
                name: 'Bombard Cannon',
                img: 'FragmentationBombs',
                reforgedImg: '',
                doubledName: 'Double Bombard Cannon',
                doubledImg: 'DoubleBombardCannon',
                doubledReforgedImg: '',
                damage: 35,
                range: 1500,
                cooldown: 1,
                dps: 35
            },{
                id: 111,
                type: SHIP_ONLY,
                price: 1500,
                finally: false,
                name: 'Boulder Cannon',
                img: 'GolemStormBolt',
                reforgedImg: '',
                doubledName: 'Double Boulder Cannon',
                doubledImg: 'DoubleBoulderCannon',
                doubledReforgedImg: '',
                damage: 35,
                range: 1500,
                cooldown: 1,
                dps: 35
            }
        ]
    }
]